import type { Album, Artist, PlaylistSearchItem, SearchParams, SearchResponse, Track } from '@/types/music';
import { extensionCoreBridge } from '@/lib/extensions/extension-core-bridge';
import { extensionCapabilityNames, getExtensionCompatibilityError, type InstalledExtension } from '@/lib/extensions/extension-types';
import { ProviderRegistry, type ProviderAdapter, type ProviderCapability } from './provider-registry';

type LooseRecord = Record<string, unknown>;
const stringValue = (record: LooseRecord, ...keys: string[]): string => { for (const key of keys) if (typeof record[key] === 'string' && record[key]) return record[key] as string; return ''; };
const numberValue = (record: LooseRecord, ...keys: string[]): number => { for (const key of keys) if (typeof record[key] === 'number' && Number.isFinite(record[key])) return record[key] as number; return 0; };
const audioMetaFor = (record: LooseRecord): Track['audioMeta'] => { const nested = record.audio_meta && typeof record.audio_meta === 'object' ? record.audio_meta as LooseRecord : record.audioMeta && typeof record.audioMeta === 'object' ? record.audioMeta as LooseRecord : record; const bpm = numberValue(nested, 'bpm', 'tempo') || numberValue(record, 'bpm', 'tempo'); const key = stringValue(nested, 'key', 'musical_key') || stringValue(record, 'key', 'musical_key'); const keyScale = stringValue(nested, 'keyScale', 'key_scale', 'mode') || stringValue(record, 'keyScale', 'key_scale', 'mode'); return bpm > 0 || key ? { bpm: bpm || null, key: key || null, keyScale: keyScale || null, source: 'provider' } : null; };
const imagesFor = (record: LooseRecord): Track['images'] => { const raw = record.images ?? record.image ?? record.cover_url ?? record.coverUrl; const url = typeof raw === 'string' ? raw : ''; if (raw && typeof raw === 'object' && Array.isArray(raw)) { const first = raw.find((entry) => entry && typeof entry === 'object' && typeof (entry as LooseRecord).url === 'string') as LooseRecord | undefined; return imagesFor({ cover_url: first ? first.url : '' }); } return { small: url, thumbnail: url, large: url, back: null }; };
export function normalizeExtensionTrack(raw: unknown, providerId: string): Track { const record = raw && typeof raw === 'object' ? raw as LooseRecord : {}; const artists = Array.isArray(record.artists) ? record.artists : []; const artist = typeof record.artists === 'string' ? record.artists : artists.map((entry) => typeof entry === 'string' ? entry : stringValue((entry ?? {}) as LooseRecord, 'name')).filter(Boolean).join(', '); const images = imagesFor(record); const duration = numberValue(record, 'duration_ms', 'durationMs', 'duration'); return { id: stringValue(record, 'id', 'provider_track_id', 'track_id') || `${providerId}:${stringValue(record, 'name', 'title')}`, provider: providerId, title: stringValue(record, 'name', 'title') || 'Untitled', artist: artist || stringValue(record, 'artist', 'artist_name') || 'Unknown artist', artistId: numberValue(record, 'artist_id'), albumTitle: stringValue(record, 'album_name', 'albumTitle', 'album'), albumCover: images.large, albumId: stringValue(record, 'album_id'), releaseDate: stringValue(record, 'release_date'), genre: stringValue(record, 'genre'), duration, audioQuality: { maximumBitDepth: 0, maximumSamplingRate: 0, isHiRes: false }, version: null, label: stringValue(record, 'label'), labelId: 0, upc: stringValue(record, 'upc'), mediaCount: 1, parental_warning: Boolean(record.explicit), streamable: true, purchasable: false, previewable: false, genreId: 0, genreSlug: '', genreColor: '', releaseDateStream: stringValue(record, 'release_date'), releaseDateDownload: '', maximumChannelCount: 2, images, isrc: stringValue(record, 'isrc'), audioMeta: audioMetaFor(record), isVideo: record.isVideo === true || record.is_video === true }; }
function normalizeResponse(raw: unknown, providerId: string): SearchResponse { const tracks = Array.isArray(raw) ? raw.map((item) => normalizeExtensionTrack(item, providerId)) : []; return { tracks, albums: [] as Album[], artists: [] as Artist[], playlists: [] as PlaylistSearchItem[], pagination: { offset: 0, total: tracks.length, hasMore: false } }; }
function getUrl(raw: unknown): string { const record = raw && typeof raw === 'object' ? raw as LooseRecord : {}; const track = record.track && typeof record.track === 'object' ? record.track as LooseRecord : record; return stringValue(track, 'stream_url', 'audio_url', 'url', 'preview_url'); }
export function createExtensionProviderAdapter(extension: InstalledExtension): ProviderAdapter { const id = extension.id; const types = new Set([...(extension.types ?? []), ...extensionCapabilityNames(extension.capabilities)]); const supportsMetadata = extension.has_metadata_provider === true || types.has('metadata_provider'); const supportsDownload = extension.has_download_provider === true || types.has('download_provider'); const capabilities = new Set<ProviderCapability>(); if (supportsMetadata) capabilities.add('search').add('stream').add('home'); if (supportsMetadata || supportsDownload) capabilities.add('download'); return { id, displayName: extension.display_name || extension.name || id, capabilities, search: async (params: SearchParams) => params.type && params.type !== 'track' ? normalizeResponse([], id) : normalizeResponse(await extensionCoreBridge.searchMetadataProvider(id, params.q, 20), id), searchTracks: async (query: string, _page = 1, limit = 20) => normalizeResponse(await extensionCoreBridge.searchMetadataProvider(id, query, limit), id), getStreamUrl: async (trackId: string) => { const url = getUrl(await extensionCoreBridge.getProviderMetadata(id, 'track', trackId)); if (!url) throw new Error(`Extension provider ${id} returned no stream URL`); return url; }, getDownloadUrl: async (trackId: string) => { const url = getUrl(await extensionCoreBridge.getProviderMetadata(id, 'track', trackId)); if (!url) throw new Error(`Extension provider ${id} returned no download URL`); return url; } }; }
const registeredExtensionProviders = new Set<string>();
export async function syncExtensionProviders(appVersion?: string): Promise<void> { if (!extensionCoreBridge.isAvailable()) return; if (appVersion?.trim()) await extensionCoreBridge.setAppVersion(appVersion); const installed = await extensionCoreBridge.getInstalled(); for (const providerId of registeredExtensionProviders) ProviderRegistry.unregister(providerId); registeredExtensionProviders.clear(); for (const extension of installed) { const types = new Set([...(extension.types ?? []), ...extensionCapabilityNames(extension.capabilities)]); if (!extension.enabled || getExtensionCompatibilityError(extension, appVersion) || (!extension.has_metadata_provider && !types.has('metadata_provider'))) continue; ProviderRegistry.register(createExtensionProviderAdapter(extension)); registeredExtensionProviders.add(extension.id); } }
